from . import general_command
from . import banxa_handler
from . import mercuryo_handler
from . import koinal_handler
from . import bestchange_handler
from . import compare_handler
from . import setSettings
from . import callback_query_handler
from . import default_handler